#!/usr/bin/env python3
"""Derives the fork revision -> upstream version tables of the identifier database.

Run through scripts/regen-version-tables.sh, which fetches the Zephyr manifests first. Python 3
standard library only.

    version-tables.py --manifests DIR --db FILE --pins FILE --cache DIR
    version-tables.py --self-test          # offline checks of the parsers; no network

For every Zephyr release whose `west.yml` is in DIR, every pinned revision of every module in
DERIVE gets an upstream version, by one of:

  file    read a version file of the fork at that revision (raw.githubusercontent.com) and
          match a regex; the version is built from the named groups with `fmt`.
  tag     the newest upstream release tag (matching `tag`) that is an ancestor of the fork
          revision, found in a blobless clone (`git fetch --filter=tree:0`) of fork + upstream.
  self    the module is its own upstream (a Zephyr-maintained aggregate of vendor code); the
          version is the commit itself.
  log     the version in the newest commit subject of the fork (matching `regex`), for forks
          that import upstream releases as snapshots and name the release when they do.
  manual  nothing is derived; every pinned revision must already have a hand-curated row
          (outside the generated markers) in FILE, citing its source.

The rows are written between the `# BEGIN generated` and `# END generated` markers inside
each module's `table:` in FILE; nothing else in FILE is touched. Revisions and versions are
single-quoted so a hex revision such as `1e75...` is never read as a number.

The pin list (every module, revision and the releases pinning it) is written to --pins; the
coverage tests read it offline.

Exits 1 if any pinned revision of a seeded module has no version (no silent gaps).
"""

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request

BEGIN = "# BEGIN generated by scripts/regen-version-tables.sh; do not edit"
END = "# END generated"

# module -> derivation. `repo` (for `file`) is the fork's name under zephyrproject-rtos and
# defaults to the manifest URL's last path segment.
DERIVE = {
    "mbedtls": {
        "how": "file",
        "paths": ["include/mbedtls/build_info.h", "include/mbedtls/version.h"],
        "regex": r'#define\s+MBEDTLS_VERSION_STRING\s+"(?P<v>[0-9.]+)"',
        "fmt": "{v}",
    },
    "mbedtls-3.6": {
        "how": "file",
        "paths": ["include/mbedtls/build_info.h"],
        "regex": r'#define\s+MBEDTLS_VERSION_STRING\s+"(?P<v>[0-9.]+)"',
        "fmt": "{v}",
    },
    "tf-psa-crypto": {
        "how": "file",
        "paths": ["include/tf-psa-crypto/build_info.h", "include/tf-psa-crypto/version.h"],
        "regex": r'#define\s+TF_PSA_CRYPTO_VERSION_STRING\s+"(?P<v>[0-9.]+)"',
        "fmt": "{v}",
    },
    "mcuboot": {
        "how": "file",
        "paths": ["boot/zephyr/VERSION"],
        "regex": r"VERSION_MAJOR\s*=\s*(?P<a>\d+)\s+VERSION_MINOR\s*=\s*(?P<b>\d+)\s+"
        r"PATCHLEVEL\s*=\s*(?P<c>\d+)\s+VERSION_TWEAK\s*=\s*\d+\s+EXTRAVERSION\s*=[ \t]*(?P<x>\S*)",
        "fmt": "{a}.{b}.{c}{x:+-}",
    },
    "lvgl": {
        "how": "file",
        "paths": ["lv_version.h"],
        "regex": r"LVGL_VERSION_MAJOR\s+(?P<a>\d+)\s+#define\s+LVGL_VERSION_MINOR\s+(?P<b>\d+)\s+"
        r"#define\s+LVGL_VERSION_PATCH\s+(?P<c>\d+)\s+#define\s+LVGL_VERSION_INFO\s+\"(?P<x>[^\"]*)\"",
        "fmt": "{a}.{b}.{c}{x:+-}",
    },
    "hal_nordic": {
        "how": "file",
        "paths": ["nrfx/CHANGELOG.md"],
        "regex": r"^## \[(?P<v>\d+\.\d+\.\d+)\]",
        "fmt": "{v}",
    },
    "hal_espressif": {
        "how": "file",
        "paths": ["components/esp_common/include/esp_idf_version.h"],
        "regex": [
            r"#define\s+ESP_IDF_VERSION_MAJOR\s+(?P<a>\d+)",
            r"#define\s+ESP_IDF_VERSION_MINOR\s+(?P<b>\d+)",
            r"#define\s+ESP_IDF_VERSION_PATCH\s+(?P<c>\d+)",
        ],
        # ESP-IDF tags x.y.0 releases as vX.Y, and NVD lists them as X.Y.
        "fmt": "{a}.{b}.{c}",
        "drop_zero_patch": True,
        # The header is bumped at the start of a release cycle: a fork commit made before
        # the release tag is a development snapshot.
        "release_check": {"repo": "espressif/esp-idf", "tag": "v{version}"},
    },
    "hal_rpi_pico": {
        "how": "file",
        "paths": ["pico_sdk_version.cmake"],
        "regex": [
            r"set\(PICO_SDK_VERSION_MAJOR\s+(?P<a>\d+)\)",
            r"set\(PICO_SDK_VERSION_MINOR\s+(?P<b>\d+)\)",
            r"set\(PICO_SDK_VERSION_REVISION\s+(?P<c>\d+)\)",
        ],
        "fmt": "{a}.{b}.{c}",
    },
    "hal_silabs": {
        # sl_platform_version.h holds the platform component's version, not the SDK release;
        # the import commits name the Simplicity SDK release.
        "how": "log",
        "regex": r"^simplicity_sdk: Import HAL version (?P<v>\d{4}\.\d+\.\d+)$",
    },
    "segger": {
        "how": "file",
        "paths": ["SEGGER/SEGGER_RTT.h"],
        "regex": r"SystemView version: (?P<v>\d+\.\d+[a-z]?)",
        "fmt": "{v}",
    },
    "fatfs": {
        "how": "file",
        "paths": ["include/ff.h", "ff.h"],
        "regex": r"FatFs - Generic FAT Filesystem module\s+R(?P<v>0\.\d+[a-z]?)",
        "fmt": "{v}",
    },
    "nanopb": {
        "how": "file",
        "paths": ["pb.h"],
        "regex": r'#define\s+NANOPB_VERSION\s+"?nanopb-(?P<v>[0-9][0-9A-Za-z.-]*)',
        "fmt": "{v}",
    },
    "zcbor": {
        "how": "file",
        "paths": ["zcbor/VERSION", "VERSION"],
        "regex": r"^(?P<v>\d+\.\d+\.\d+)",
        "fmt": "{v}",
    },
    "picolibc": {
        "how": "file",
        "paths": ["meson.build"],
        "regex": r"version\s*:\s*'(?P<v>\d+\.\d+(?:\.\d+)*)'",
        "fmt": "{v}",
    },
    "percepio": {
        "how": "file",
        "paths": ["TraceRecorder/include/trcRecorder.h"],
        "regex": r"Trace Recorder for Tracealyzer v(?P<v>\d+\.\d+\.\d+)",
        "fmt": "{v}",
    },
    "cmsis": {
        "how": "log",
        "regex": r"\(CMSIS (?P<v>\d+\.\d+\.\d+)\)",
    },
    "cmsis_6": {
        "how": "tag",
        "upstream": "https://github.com/ARM-software/CMSIS_6",
        "tag": r"^v(?P<v>\d+\.\d+\.\d+)$",
    },
    "cmsis-dsp": {
        "how": "tag",
        "upstream": "https://github.com/ARM-software/CMSIS-DSP",
        "tag": r"^v(?P<v>\d+\.\d+\.\d+)$",
    },
    "littlefs": {
        "how": "tag",
        "upstream": "https://github.com/littlefs-project/littlefs",
        "tag": r"^v(?P<v>\d+\.\d+\.\d+)$",
    },
    "tinycrypt": {
        "how": "file",
        "paths": ["README.zephyr"],
        "regex": r"At revision [0-9a-f]+, version (?P<v>\d+\.\d+\.\d+)",
        "fmt": "{v}",
    },
    "openthread": {
        "how": "tag",
        "upstream": "https://github.com/openthread/openthread",
        # OpenThread's releases are dated reference tags; NVD's versions are the dates.
        "tag": r"^thread-reference-(?P<y>\d{4})(?P<m>\d{2})(?P<d>\d{2})$",
        "fmt": "{y}-{m}-{d}",
    },
    "trusted-firmware-m": {
        "how": "tag",
        "upstream": "https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git",
        "tag": r"^TF-Mv(?P<v>\d+\.\d+\.\d+)$",
    },
    "tf-m-tests": {
        "how": "tag",
        "upstream": "https://git.trustedfirmware.org/TF-M/tf-m-tests.git",
        "tag": r"^TF-Mv(?P<v>\d+\.\d+\.\d+)$",
    },
    "loramac-node": {
        "how": "tag",
        "upstream": "https://github.com/Lora-net/LoRaMac-node",
        "tag": r"^v(?P<v>\d+\.\d+\.\d+)$",
    },
    "libmetal": {
        "how": "log",
        "regex": r"^lib: update libmetal to release v(?P<v>\d{4}\.\d{2}\.\d+)$",
    },
    "open-amp": {
        "how": "log",
        "regex": r"^lib: update open-amp lib to release v(?P<v>\d{4}\.\d{2}\.\d+)$",
    },
    "hostap": {
        "how": "tag",
        "upstream": "https://w1.fi/hostap.git",
        "tag": r"^hostap_(?P<a>\d+)_(?P<b>\d+)$",
        "fmt": "{a}.{b}",
    },
    "liblc3": {
        "how": "tag",
        "upstream": "https://github.com/google/liblc3",
        "tag": r"^v(?P<v>\d+\.\d+\.\d+)$",
    },
    "uoscore-uedhoc": {
        "how": "tag",
        "upstream": "https://github.com/eriptic/uoscore-uedhoc",
        "tag": r"^v(?P<v>\d+\.\d+\.\d+)$",
    },
    "hal_stm32": {"how": "self"},
    "hal_nxp": {"how": "self"},
}


# --- manifests ---------------------------------------------------------------------------


def parse_manifest(text):
    """The `projects` of a west.yml: [{name, revision, url, path}], resolving remotes.

    A small line-based reader for the subset of YAML west manifests use (block mappings and
    sequences, no anchors or flow collections inside `projects`). Raises ValueError on input
    it does not understand rather than guessing.
    """
    items = {"remotes": [], "projects": []}
    default_remote = None
    section = None
    item = None
    item_indent = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        if raw.lstrip().startswith("#"):
            continue
        line = raw.split(" #", 1)[0].rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        body = line.strip()
        if indent <= 2 and not body.startswith("-"):
            # A top-level key of `manifest:` (or `manifest:` itself) ends the current item.
            item = None
            item_indent = None
            key = body.partition(":")[0]
            section = key if key in ("remotes", "projects", "defaults") else None
            continue
        if section == "defaults":
            k, _, v = body.partition(":")
            if k.strip() == "remote":
                default_remote = v.strip()
            continue
        if section is None:
            continue
        if body.startswith("- ") and (item_indent is None or indent <= item_indent):
            item = {}
            item_indent = indent
            items[section].append(item)
            body = body[2:]
        elif item is None:
            raise ValueError(f"line {lineno}: unexpected {body!r} in {section}")
        elif indent != item_indent + 2 or body.startswith("- "):
            continue  # nested under a key of the item (groups, import allowlists)
        k, sep, v = body.partition(":")
        if not sep:
            raise ValueError(f"line {lineno}: expected 'key: value', got {body!r}")
        v = v.strip().strip("'\"")
        if v:
            item[k.strip()] = v
    remotes = {}
    for r in items["remotes"]:
        if "name" not in r or "url-base" not in r:
            raise ValueError(f"remote without name or url-base: {r}")
        remotes[r["name"]] = r["url-base"]
    out = []
    for p in items["projects"]:
        if "name" not in p:
            raise ValueError(f"project without a name: {p}")
        if "url" in p:
            url = p["url"]
        else:
            remote = p.get("remote", default_remote)
            if remote not in remotes:
                raise ValueError(f"project {p['name']}: unknown remote {remote!r}")
            url = remotes[remote].rstrip("/") + "/" + p.get("repo-path", p["name"])
        out.append(
            {
                "name": p["name"],
                "revision": p.get("revision", "main"),
                "url": url,
                "path": p.get("path", p["name"]),
            }
        )
    return out


def collect_pins(manifest_dir):
    """{module: {revision: {"url": url, "tags": [release, ...]}}} over every west-<tag>.yml."""
    pins = {}
    files = sorted(f for f in os.listdir(manifest_dir) if re.fullmatch(r"west-v[\d.]+\.yml", f))
    if not files:
        raise SystemExit(f"version-tables: no west-v*.yml in {manifest_dir}")
    for f in files:
        release = f[len("west-") : -len(".yml")]
        with open(os.path.join(manifest_dir, f), encoding="utf-8") as fh:
            for p in parse_manifest(fh.read()):
                entry = pins.setdefault(p["name"], {}).setdefault(
                    p["revision"], {"url": p["url"], "tags": []}
                )
                entry["tags"].append(release)
    for revs in pins.values():
        for entry in revs.values():
            entry["tags"].sort(key=version_key)
    return pins


def write_pins(pins, path):
    """One line per (module, revision): `module revision url release...`, sorted."""
    lines = [
        "# Generated by scripts/regen-version-tables.sh from Zephyr's west.yml; do not edit.",
        "# module revision url releases...",
    ]
    for module in sorted(pins):
        for rev in sorted(pins[module]):
            e = pins[module][rev]
            lines.append(" ".join([module, rev, e["url"], *e["tags"]]))
    write_atomic(path, ("\n".join(lines) + "\n").encode("utf-8"))


# --- derivation --------------------------------------------------------------------------


def version_key(s):
    return [int(x) if x.isdigit() else x for x in re.split(r"(\d+)", s)]


def render(fmt, groups):
    """`{name}` is the group; `{name:+-}` is `-<group>` when the group is non-empty."""

    def sub(m):
        name, mod = m.group(1), m.group(2)
        value = groups.get(name) or ""
        if mod:
            return (mod[2:] + value) if value else ""
        return value

    return re.sub(r"\{(\w+)(:\+[^}]*)?\}", sub, fmt)


def match_version(spec, text):
    """The version from `text`: every regex in `spec["regex"]` (one, or a list whose named
    groups are merged) must match; None otherwise."""
    regexes = spec["regex"] if isinstance(spec["regex"], list) else [spec["regex"]]
    groups = {}
    for regex in regexes:
        m = re.search(regex, text, re.MULTILINE)
        if not m:
            return None
        groups.update(m.groupdict())
    version = render(spec.get("fmt", "{v}"), groups)
    if spec.get("drop_zero_patch"):
        version = re.sub(r"^(\d+\.\d+)\.0$", r"\1", version)
    return version


def write_atomic(path, data):
    """Writes `data` (bytes) to `path` through a temporary file in the same directory, so an
    interrupted run never leaves a truncated file behind."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp = f"{path}.tmp.{os.getpid()}"
    with open(tmp, "wb") as fh:
        fh.write(data)
    os.replace(tmp, path)


def fetch(url, cache, cache_missing=True):
    """GET url, cached under `cache`; None on 404. A 404 is remembered by a separate
    `<file>.404` marker only when `cache_missing` (right for content at a fixed commit, wrong
    for things that may appear later, such as a release tag). Network failures and timeouts
    raise LookupError."""
    key = re.sub(r"[^A-Za-z0-9._-]", "_", url)
    path = os.path.join(cache, "http", key)
    missing = f"{path}.404"
    if os.path.exists(path):
        with open(path, "rb") as fh:
            return fh.read().decode("utf-8", "replace")
    if cache_missing and os.path.exists(missing):
        return None
    headers = {"User-Agent": "rollcall-version-tables"}
    token = os.environ.get("GITHUB_TOKEN")
    if token and ("githubusercontent.com" in url or "api.github.com" in url):
        headers["Authorization"] = f"token {token}"
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            data = r.read()
    except urllib.error.HTTPError as e:
        if e.code == 404:
            if cache_missing:
                write_atomic(missing, b"")
            return None
        raise LookupError(f"{url}: HTTP {e.code}") from None
    except (urllib.error.URLError, TimeoutError, OSError) as e:
        raise LookupError(f"{url}: {getattr(e, 'reason', e)}") from None
    write_atomic(path, data)
    return data.decode("utf-8", "replace")


def github_json(path, cache, cache_missing=True):
    """A GitHub REST API object (`path` under https://api.github.com/), or None on 404."""
    text = fetch(f"https://api.github.com/{path}", cache, cache_missing)
    if text is None:
        return None
    try:
        return json.loads(text)
    except ValueError:
        raise LookupError(f"api.github.com/{path}: not JSON") from None


def mark_unreleased(version, fork_date, tag_date):
    """`version` if its release tag existed at the fork commit's date, else `version-dev`:
    a fork commit that predates the release is a development snapshot of it. Dates are
    ISO 8601 UTC strings (`2026-08-25T10:00:00Z`), which compare correctly as text."""
    if tag_date is not None and tag_date <= fork_date:
        return version
    return f"{version}-dev"


def release_date(repo, tag, cache):
    """When `tag` was made in GitHub `repo` (tagger date of an annotated tag, else the
    commit date), or None if the tag does not exist (not cached: it may appear later)."""
    ref = github_json(f"repos/{repo}/git/ref/tags/{tag}", cache, cache_missing=False)
    if ref is None or "object" not in ref:
        return None
    obj = ref["object"]
    if obj.get("type") == "tag":
        tag_obj = github_json(f"repos/{repo}/git/tags/{obj['sha']}", cache)
        return tag_obj["tagger"]["date"]
    commit = github_json(f"repos/{repo}/git/commits/{obj['sha']}", cache)
    return commit["committer"]["date"]


def commit_date(url, rev, cache):
    owner, repo = fork_repo(url)
    commit = github_json(f"repos/{owner}/{repo}/git/commits/{rev}", cache)
    if commit is None:
        raise LookupError(f"{url} {rev}: commit not found")
    return commit["committer"]["date"]


def fork_repo(url):
    m = re.fullmatch(r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?/?", url)
    if not m:
        raise ValueError(f"not a GitHub URL: {url}")
    return m.group(1), m.group(2)


def derive_file(spec, url, rev, cache):
    owner, repo = fork_repo(url)
    tried = []
    for p in spec["paths"]:
        text = fetch(f"https://raw.githubusercontent.com/{owner}/{repo}/{rev}/{p}", cache)
        if text is None:
            tried.append(f"{p} (absent)")
            continue
        v = match_version(spec, text)
        if v:
            check = spec.get("release_check")
            if check:
                tag = check["tag"].format(version=v)
                tagged = release_date(check["repo"], tag, cache)
                v2 = mark_unreleased(v, commit_date(url, rev, cache), tagged)
                if v2 != v:
                    return v2, f"{p} (upstream {tag} not yet released at the fork commit)"
            return v, f"{p}"
        tried.append(f"{p} (no match)")
    raise LookupError("; ".join(tried))


def git(repo, *args):
    return subprocess.run(
        ["git", "-C", repo, *args], check=True, capture_output=True, text=True
    ).stdout


def ensure_commits(module, url, revs, cache):
    """A bare repository under `cache` holding the fork's `revs` and their history (commits
    only: `--filter=tree:0`)."""
    repo = os.path.join(cache, "git", module)
    if not os.path.isdir(repo):
        os.makedirs(repo)
        git(repo, "init", "-q", "--bare")
    missing = []
    for rev in revs:
        try:
            git(repo, "cat-file", "-e", f"{rev}^{{commit}}")
        except subprocess.CalledProcessError:
            missing.append(rev)
    if missing:
        git(repo, "fetch", "-q", "--filter=tree:0", url, *missing)
    return repo


def derive_tag(module, spec, url, revs, cache):
    """{rev: (version, tag)} for every rev, from a blobless clone of fork + upstream."""
    repo = ensure_commits(module, url, revs, cache)
    # Every run: an upstream release made since the last run must be seen (fetching into an
    # existing clone only transfers what is new; --prune drops tags upstream deleted).
    git(
        repo, "fetch", "-q", "--prune", "--filter=tree:0", "--no-tags", spec["upstream"],
        "+refs/tags/*:refs/tags/*",
    )
    tag_re = re.compile(spec["tag"])
    out = {}
    for rev in revs:
        tags = git(repo, "tag", "--merged", rev).split()
        best = None
        for t in tags:
            m = tag_re.match(t)
            if not m:
                continue
            v = render(spec.get("fmt", "{v}"), m.groupdict())
            if best is None or version_key(v) > version_key(best[0]):
                best = (v, t)
        if best is None:
            raise LookupError(f"{module} {rev}: no tag matching {spec['tag']} is an ancestor")
        out[rev] = best
    return out


def derive_log(module, spec, url, revs, cache):
    """{rev: (version, subject)}: the version in the newest commit subject (first-parent
    order from the revision) matching `regex`, for forks that import upstream releases as
    snapshots and say so in the commit message."""
    repo = ensure_commits(module, url, revs, cache)
    out = {}
    for rev in revs:
        for subject in git(repo, "log", "--first-parent", "--format=%s", rev).splitlines():
            m = re.search(spec["regex"], subject)
            if m:
                out[rev] = (render(spec.get("fmt", "{v}"), m.groupdict()), subject)
                break
        else:
            raise LookupError(f"{module} {rev}: no commit subject matches {spec['regex']}")
    return out


# --- the database file -------------------------------------------------------------------


def module_blocks(lines):
    """{module: (start, end)} line ranges of each `  <module>:` entry under `modules:`."""
    blocks = {}
    current = None
    for i, line in enumerate(lines):
        m = re.match(r"^  ([A-Za-z0-9_.+-]+):\s*$", line)
        if m:
            if current:
                blocks[current[0]] = (current[1], i)
            current = (m.group(1), i)
        elif current and line and not line.startswith(" ") and not line.startswith("#"):
            blocks[current[0]] = (current[1], i)
            current = None
    if current:
        blocks[current[0]] = (current[1], len(lines))
    return blocks


ROW = re.compile(r"^\s+'([^']+)':\s*'([^']+)'")


def hand_rows(lines, start, end):
    """Revisions listed in the module's table outside the generated markers."""
    rows = {}
    inside = False
    for line in lines[start:end]:
        if line.strip() == BEGIN:
            inside = True
        elif line.strip() == END:
            inside = False
        elif not inside:
            m = ROW.match(line)
            if m:
                rows[m.group(1)] = m.group(2)
    return rows


def rewrite_generated_rows(text, generated):
    """Replaces the marker region of each module in `generated` ({module: [(rev, version,
    comment)]}). Raises ValueError if a module lacks its markers."""
    lines = text.split("\n")
    blocks = module_blocks(lines)
    # Rewrite bottom-up so earlier ranges stay valid.
    for module in sorted(generated, key=lambda m: blocks.get(m, (0, 0))[0], reverse=True):
        if module not in blocks:
            raise ValueError(f"module {module} is not in the database")
        start, end = blocks[module]
        try:
            b = next(i for i in range(start, end) if lines[i].strip() == BEGIN)
            e = next(i for i in range(b, end) if lines[i].strip() == END)
        except StopIteration:
            raise ValueError(f"module {module}: no generated markers in its table") from None
        indent = lines[b][: len(lines[b]) - len(lines[b].lstrip())]
        rows = [
            f"{indent}'{rev}': '{version}'" + (f"  # {comment}" if comment else "")
            for rev, version, comment in sorted(generated[module])
        ]
        lines[b + 1 : e] = rows
    return "\n".join(lines)


# --- main --------------------------------------------------------------------------------


def run(args):
    pins = collect_pins(args.manifests)
    write_pins(pins, args.pins)
    with open(args.db, encoding="utf-8") as fh:
        text = fh.read()
    lines = text.split("\n")
    blocks = module_blocks(lines)
    generated = {}
    gaps = []
    for module in sorted(blocks):
        if module not in pins:
            continue  # not pinned by these releases (cjson); its rule is git_tag
        start, end = blocks[module]
        has_markers = any(lines[i].strip() == BEGIN for i in range(start, end))
        spec = DERIVE.get(module, {"how": "manual"})
        hand = hand_rows(lines, start, end)
        revs = sorted(pins[module])
        rows = []
        if spec["how"] == "manual" or not has_markers:
            for rev in revs:
                if rev not in hand:
                    gaps.append(f"{module} {rev}: no hand-curated row")
            continue
        results = {}
        todo = [r for r in revs if r not in hand]
        try:
            if spec["how"] == "file":
                for rev in todo:
                    url = pins[module][rev]["url"]
                    v, where = derive_file(spec, url, rev, args.cache)
                    results[rev] = (v, where)
            elif spec["how"] == "tag":
                if todo:
                    url = pins[module][todo[0]]["url"]
                    for rev, (v, tag) in derive_tag(module, spec, url, todo, args.cache).items():
                        results[rev] = (v, f"newest ancestor tag {tag}")
            elif spec["how"] == "log":
                if todo:
                    url = pins[module][todo[0]]["url"]
                    for rev, (v, subject) in derive_log(module, spec, url, todo, args.cache).items():
                        results[rev] = (v, f"fork commit {subject!r}")
            elif spec["how"] == "self":
                for rev in todo:
                    results[rev] = (rev, "the module is its own upstream")
        except (LookupError, ValueError, subprocess.CalledProcessError) as e:
            detail = getattr(e, "stderr", None) or str(e)
            gaps.append(f"{module}: {detail.strip()}")
            continue
        for rev in todo:
            v, why = results[rev]
            rows.append((rev, v, f"{' '.join(pins[module][rev]['tags'])}; {why}"))
        generated[module] = rows
        for rev in revs:
            v = hand.get(rev) or results[rev][0]
            print(f"{module:20} {rev[:12]:12} {v:24} {' '.join(pins[module][rev]['tags'])}")
    new = rewrite_generated_rows(text, generated)
    if new != text:
        write_atomic(args.db, new.encode("utf-8"))
    if gaps:
        print("version-tables: pinned revisions without a version:", file=sys.stderr)
        for g in gaps:
            print(f"  {g}", file=sys.stderr)
        return 1
    return 0


SELF_TEST_MANIFEST = """\
manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: other
      url-base: https://example.org/git/

  group-filter: [-optional]

  projects:
    - name: hal_nordic
      revision: 44fd3d44b15cb75f80a25b4679f91d2787e28664
      path: modules/hal/nordic
      groups:
        - hal
    - name: mbedtls
      revision: a3e190fe44c78d1ba67f55979e1257328cc7d0d8 # comment
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: thing
      remote: other
      repo-path: thing-repo
      revision: v1.2.3
    - name: direct
      url: https://example.com/direct.git
      revision: 'abc'
      import:
        name-allowlist:
          - x
  self:
    path: zephyr
"""


def self_test():
    projects = parse_manifest(SELF_TEST_MANIFEST)
    assert projects == [
        {
            "name": "hal_nordic",
            "revision": "44fd3d44b15cb75f80a25b4679f91d2787e28664",
            "url": "https://github.com/zephyrproject-rtos/hal_nordic",
            "path": "modules/hal/nordic",
        },
        {
            "name": "mbedtls",
            "revision": "a3e190fe44c78d1ba67f55979e1257328cc7d0d8",
            "url": "https://github.com/zephyrproject-rtos/mbedtls",
            "path": "modules/crypto/mbedtls",
        },
        {
            "name": "thing",
            "revision": "v1.2.3",
            "url": "https://example.org/git/thing-repo",
            "path": "thing",
        },
        {"name": "direct", "revision": "abc", "url": "https://example.com/direct.git", "path": "direct"},
    ], projects
    for bad in [
        "manifest:\n  projects:\n    - path: x\n",
        "manifest:\n  projects:\n    - name: x\n      remote: nowhere\n",
        "manifest:\n  projects:\n    oops\n",
    ]:
        try:
            parse_manifest(bad)
        except ValueError:
            pass
        else:
            raise AssertionError(f"accepted {bad!r}")
    assert parse_manifest("") == []

    # Version formats.
    mcuboot = DERIVE["mcuboot"]
    text = "VERSION_MAJOR = 2\nVERSION_MINOR = 4\nPATCHLEVEL = 0\nVERSION_TWEAK = 0\nEXTRAVERSION =\n"
    assert match_version(mcuboot, text) == "2.4.0", match_version(mcuboot, text)
    text = text.replace("EXTRAVERSION =", "EXTRAVERSION = rc1")
    assert match_version(mcuboot, text) == "2.4.0-rc1"
    assert match_version(DERIVE["mbedtls"], '#define MBEDTLS_VERSION_STRING         "3.6.4"') == "3.6.4"
    assert match_version(DERIVE["hal_nordic"], "# Changelog\n## [Unreleased]\n## [4.2.0] - 2026\n## [4.1.0]") == "4.2.0"
    assert match_version(DERIVE["mbedtls"], "nothing here") is None
    assert render("{a}.{b}", {"a": "2", "b": "11"}) == "2.11"
    esp = "#define ESP_IDF_VERSION_MAJOR   6\n/** c */\n#define ESP_IDF_VERSION_MINOR   1\n#define ESP_IDF_VERSION_PATCH   0\n"
    assert match_version(DERIVE["hal_espressif"], esp) == "6.1"
    assert match_version(DERIVE["hal_espressif"], esp.replace("PATCH", "X")) is None
    assert match_version(DERIVE["hal_espressif"], esp.replace("PATCH   0", "PATCH   2")) == "6.1.2"

    # Rewriting only touches the marker region.
    db = "\n".join(
        [
            "schema: 1",
            "modules:",
            "  a:",
            "    version_rule:",
            "      kind: manual",
            "      table:",
            "        'hand': '1.0'  # source: https://example.org",
            f"        {BEGIN}",
            "        'old': '0.1'",
            f"        {END}",
            "  b:",
            "    version_rule:",
            "      kind: git_tag",
            "",
        ]
    )
    lines = db.split("\n")
    assert set(module_blocks(lines)) == {"a", "b"}
    assert hand_rows(lines, *module_blocks(lines)["a"]) == {"hand": "1.0"}
    new = rewrite_generated_rows(db, {"a": [("1e75", "2.0", "v4.4.0"), ("0abc", "1.5", None)]})
    assert "        '0abc': '1.5'\n        '1e75': '2.0'  # v4.4.0\n" in new, new
    assert "'old'" not in new and "'hand': '1.0'" in new
    assert rewrite_generated_rows(new, {"a": [("1e75", "2.0", "v4.4.0"), ("0abc", "1.5", None)]}) == new
    try:
        rewrite_generated_rows(db, {"b": []})
    except ValueError:
        pass
    else:
        raise AssertionError("module without markers accepted")
    # A version whose release tag came after the fork commit (or does not exist) is a
    # development snapshot.
    assert mark_unreleased("6.1", "2026-07-01T00:00:00Z", "2026-08-25T09:00:00Z") == "6.1-dev"
    assert mark_unreleased("6.1", "2026-07-01T00:00:00Z", None) == "6.1-dev"
    assert mark_unreleased("5.1.6", "2026-07-01T00:00:00Z", "2025-03-01T00:00:00Z") == "5.1.6"
    assert mark_unreleased("5.1.6", "2025-03-01T00:00:00Z", "2025-03-01T00:00:00Z") == "5.1.6"

    # Cache writes are atomic and a 404 marker is a separate file.
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        target = os.path.join(tmp, "sub", "file")
        write_atomic(target, b"\0404")
        with open(target, "rb") as fh:
            assert fh.read() == b"\0404"  # content that looked like the old sentinel is kept
        assert os.listdir(os.path.dirname(target)) == ["file"]
        # A cached 404 marker answers without the network; content wins over a marker.
        url = "https://raw.githubusercontent.com/o/r/abc/missing.h"
        key = re.sub(r"[^A-Za-z0-9._-]", "_", url)
        write_atomic(os.path.join(tmp, "http", key + ".404"), b"")
        assert fetch(url, tmp) is None
        write_atomic(os.path.join(tmp, "http", key), b"\0404")
        assert fetch(url, tmp) == "\0404"
        # An unreachable host is a LookupError, not a crash.
        try:
            fetch("http://127.0.0.1:9/nothing", tmp)
        except LookupError:
            pass
        else:
            raise AssertionError("unreachable host did not raise LookupError")
    print("version-tables self-test: PASS")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--manifests")
    ap.add_argument("--db")
    ap.add_argument("--pins")
    ap.add_argument("--cache")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    if not all([args.manifests, args.db, args.pins, args.cache]):
        ap.error("--manifests, --db, --pins and --cache are required")
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
